### PR TITLE
Fix mojang status

### PR DESCRIPTION
**Pull request by lucas-luchack**
Proposal for a fix

### CODE REVIEW

**Review by dscalzi — CHANGES_REQUESTED** [review]
I am going to be pushing changes.

**Comment by dscalzi** [comment]
@lucas-luchack can you allow pushes on the PR pls

**Comment by lucas-luchack** [comment]
> @lucas-luchack can you allow pushes on the PR pls

I can't see the checkbox to change that, idk why...

**Comment by lucas-luchack** [comment]
GitHub Screenshot

**Comment by dscalzi** [comment]
try in a web browser maybe https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by lucas-luchack** [comment]
> try in a web browser maybe https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

I was on my computer... Do you want me to do the PR again?

**Comment by lucas-luchack** [comment]
Okay, I fix the problem

It was because the fork was on an organization and not my personal account. Now it works. Sorry again for the wait...

**Comment by dscalzi** [comment]
Works for me, the status check system is not ideal but I'm not too worried about it right now.

**Review by dscalzi — APPROVED** [review]

**Pull request merged**
